### ISSUE TITLE
Is there in this World a virus free miner?

### ISSUE THREAD

**Issue by blueavenue** [zone117x/cryptonote-easy-miner#16]
This miner, all miners are infected. Someone knows a miner without Bitcoin Gen or other bad things?

**Comment by Cambridgeport90** [comment]
I'm seeing the same thing. It's not pretty. I don't like it much either.

**Comment by zone117x** [comment]
https://github.com/zone117x/cryptonote-easy-miner/issues/7#issuecomment-343186293
