### ISSUE TITLE
cryptonote-easy-miner_v0.0.3.zip is malicious, and Chrome has blocked it.

### ISSUE THREAD

**Issue by dimplesnyc77** [zone117x/cryptonote-easy-miner#2]
"cryptonote-easy-miner_v0.0.3.zip is malicious, and Chrome has blocked it."

why does it say that?

**Comment by zone117x** [comment]
Chrome does that all the time. Google it and you'll find tons of false positives for all sorts of projets. The C# code for this project is a simple wrapper around the native binaries. Check the C# source, even decompile the release build, and you won't find anything malicious. However, the native binaries for cpuminer and simplewallet that it ships with I cannot guarantee as I have not audited their source and I used their official compiled binaries. I'd recommend sending the release file to VirusTotal to verify if there is actually something going on. Let me know if anything comes up.

**Comment by dimplesnyc77** [comment]
Thank you for quick reply.

I checked it with Kaspersky - looks clean - I trust it.

Another question about the wallet: So I installed it, and it is running (I put in mine.moneropool.com, port 3333) - so it has the payment address on top. I tried to open simplewallet that was included with the "wallet" file and password "x".  The wallet tells me that it failed to connect to daemon at localhost:18081

What do I need to do?

Thank you.

---

On Tue, 7/5/16, Matthew Little notifications@github.com wrote:

 Subject: Re: [zone117x/cryptonote-easy-miner] cryptonote-easy-miner_v0.0.3.zip is malicious, and Chrome has blocked it. (#2)
 To: "zone117x/cryptonote-easy-miner" cryptonote-easy-miner@noreply.github.com
 Cc: "dimplesnyc77" dimplesnyc77@yahoo.com, "Author" author@noreply.github.com
 Date: Tuesday, July 5, 2016, 9:30 AM

 Chrome does that all the time.
 The C# code for this project is a simple wrapper around the
 native binaries. Check the C# source, event decompile the
 release, and you won't find anything malicious. However,
 the native binaries it ships with I cannot guarantee as I
 have not audited their source and I used their official
 compiled binaries. I'd recommend sending the release
 file to VirusTotal to verify if there is actually something
 going on. Let me know if anything comes up.

 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by zone117x** [comment]
This is using quite old versions of the wallet and cpuminer binary. Simplewallet is probably too old and unsupported with the daemon, and the cpuminer is probably really inefficient compared to letest. I would recommend following tutorials to use the latest ones via command line - or there may be more up-to-date GUIs for these programs.

**Comment by dimplesnyc77** [comment]
I think you forgot to attach the link to the tutorials.

---

On Tue, 7/5/16, Matthew Little notifications@github.com wrote:

 Subject: Re: [zone117x/cryptonote-easy-miner] cryptonote-easy-miner_v0.0.3.zip is malicious, and Chrome has blocked it. (#2)
 To: "zone117x/cryptonote-easy-miner" cryptonote-easy-miner@noreply.github.com
 Cc: "dimplesnyc77" dimplesnyc77@yahoo.com, "Author" author@noreply.github.com
 Date: Tuesday, July 5, 2016, 12:36 PM

 This is using quite old versions
 of the wallet and cpuminer binary. Simplewallet is probably
 too old and unsupported with the daemon, and the cpuminer is
 probably really inefficient compared to letest. I would
 recommend following tutorials to use the latest ones via
 command line - or there may be more up-to-date GUIs for
 these programs.

 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by zone117x** [comment]
https://monerobase.com/Simplewallet
Examples of using CPUminer and others at bottom of most monero pool websites, like this one: https://moneropool.com/#getting_started
