### ISSUE TITLE
Having issues downloading -- Chrome flagging as a virus

### ISSUE THREAD

**Issue by sloppycoffee** [zone117x/cryptonote-easy-miner#3]
Both firefox and chrome flagging the file as a virus and deletes it. Why is that?

**Comment by mizike29** [comment]
It will flag it just as antivirus will so make sure to allow it. Any EXE or anything running a command line or bat file will be false positives.  Download, allow in antivirus and start mining

**Comment by JamesCullum** [comment]
Same for Symantec Endpoint Protection. And no, not everything running a command line will be a false positive - the Monero core is a command line and doesnt get positives.

Btw the antivirus flags minerd.exe from the cpuminer binaries.

**Comment by mizike29** [comment]
Not worth mining them now anyways. Takes forever. Just buy some like I did. Then hold them until a big spike. Already up 60 percent in a day

Sent from my Verizon, Samsung Galaxy smartphone

-------- Original message --------

**Comment by JamesCullum** [comment]
Why do you even bother posting on GitHub if you have absolutely no idea about development, why issues occure and if you give absolute nonsense advice that has nothing to do with the problem?

**Comment by mizike29** [comment]
What are you talking about? Pretty sure i already commented on this and said ignore it add to you anti virus exclusions or disable during install that the exe is always seen as a virus and is a false positive.  Doesn't change the fact that mining difficulty is already way to high to mine with a cup genius.

Sent from my Verizon, Samsung Galaxy smartphone

-------- Original message --------

**Comment by mizike29** [comment]
No not everything will but everything that you are running on purpose that is an exe or command line that avast or McAfee or chrome may see it as a virus will be a false positive. I'll change the wording to be more specific for James since he wants to get way to detailed for a question from an obvious new user trying to run software that gets flagged as a false positive. I kept it simple. Ignore it. Allow It. Download. Then tried to help as mining is pointless now. You will spend more on electricity and take over a week to mine 1 monero at this point. So just invest or mine a different altcoin.

**Comment by mizike29** [comment]
Slayorktc don't use the crypto easy miner if your going to mine with your cpu it is much slower as well. Use cpuminer by wolf. It doubles the speed of mining and is coded better but it still takes way too long to mine. Easy miner is the simplest version to use however but if you look on bitcointalk and just follow the steps you can easily be mining using cpuminer by wolf or gpu mine if you can it is extremely faster but as i said before for monero your looking at 1 to 7 days for 1 monero miner in reality now so mine another bitcoin or just purchase bitcoin to monero.

**Comment by sloppycoffee** [comment]
I should have updated this thread. First, a quick Google search showed how to disable chrome from blocking the download. Second, I ended up going with a Nvidia gpu miner but after 3 days, I didn't see any return. I kind of gave up on mining and just bought more XMR to hold.

**Comment by mizike29** [comment]
That sounds like what I said LOL. Yeah I did the same, running at 270 H/s you still couldnt get anything for a good week.  So buying them at 7 bux or 8 bux even, I got mine at 7 bux, and now they hit 14 bux today, so a good investement.  Just swap them out quick at the higher price, buy again and keep doing that until your working with just profit.

**Comment by mizike29** [comment]
Hey slayorktc. How did you buy monero? I used coinbase to buy bitcoin then used shapeshifter to transfer bitcoin to my monero wallet.  It wasn't super easy with all the coinbase verifications and transaction limits plus using two sites but took about an hour total. Did you find an easier faster method?  Thanks

Sent from my Verizon, Samsung Galaxy smartphone

-------- Original message --------

**Comment by sloppycoffee** [comment]
That's basically what I did to. The shapeshift limit is annoying. Reddit might help with that. My idea would be going through a large exchange instead.

**Comment by mizike29** [comment]
The coinbase limit killed me even though i did every identity thing on the planet

Sent from my Verizon, Samsung Galaxy smartphone

-------- Original message --------

**Comment by sloppycoffee** [comment]
You could always just got through local Bitcoin? Poloenix exchange might be worth looking into it.

**Comment by zone117x** [comment]
https://github.com/zone117x/cryptonote-easy-miner/issues/7#issuecomment-343186293
