### ISSUE TITLE
minerd thrated as virus ?

### ISSUE THREAD

**Issue by tarikelbannany** [zone117x/cryptonote-easy-miner#6]
minerd thrated as virus ?   its a virus or what 
what should i do ?

thanks.

**Comment by ghost** [comment]
I hav windows 10 and all so get the same result as Trojan in the application and it automaticly remove it from the server,  but I have install it but then I get a Trojan horse on your windows

**Comment by edv-skl** [comment]
Having the same issue.

**Comment by zone117x** [comment]
Please do some research on the countless other issues on this and other repos with mining software. This does not contain a virus. 
Figure out how to control your OS anti-malware system or compile the miner from source.

https://github.com/zone117x/cryptonote-easy-miner/issues/7#issuecomment-343186293
